dist: xenial

language: java
install: true

matrix: 
  include: 
  - jdk: oraclejdk9

script: 
  - git config --global push.default simple
  - export GIT_TAG=$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
  - ant clean
  - ant compile
  - ant jar
  - ant run
  - tar -zcf pizza_reports.tar.gz build
  - tar -zcf pizza_executable_distributions.tar.gz build
